#+TITLE: Takeaway from four years in ACORN Sheffield

* Optimism: Generation 1 of ACORN Sheffield
I joined ACORN Sheffield in late 2020 and attended my first Annual General Meeting (AGM) on zoom. At the time I joined I was impressed. The branch had recently won a campaign in Park Hill tower block that had used a rent strike successfully to stop utility bills being raised. The AGM had 100 people in attendence. Every committee position was contested and there many people who seemed extremely capable organisers who spoke with clarity and vision. At about this point the union had grown rapidly and was at 400 members. 

My involvement at first was fairly minimal. I was (am) young, inexperienced, and didn't think I needed to contribute much I was happy to just observe and learn. I was put in touch with my Ward Rep in Sharrow and given leaflets to distribute in my street. I went door knocking in Broomhill talking with residents mainly about their bins and trying to get sign ups. My involvement didn't really extend beyond this and lurking on the all members general WhatsApp group. 

From the period of late 2021 to early/(mid? not 100% sure) 2022 the branch was haemorraging its active members. Half of the committee quit. The new committee then decided (without consulting membership) to delete the all members WhatsApp group'.

Being a peripheral, mostly inactive member, I am completely oblivious to all of this. All I remember feeling at this time was a of growing sense of distance to ACORN that I couldn't explain; I only realised months later that this had been caused by this deletion of the ACORN WhatsApp group (if not the mass exodus of the core active membership of who used to use it). 

* Confusion: Generation 2 of ACORN Sheffield
I received a phonecall out of the blue (sometime Spring 2022) it was an ACORN Sheffield committee member who was phoning for the next AMM. There was at most 10 of us and I didn't recognise anyone. My first thought was "where has everyone gone?"

Getting involved in an ACORN branch that had just been decimated and then started up again was bewildering. There was no acknowledgement that /something/ had just happened and it had undone the past several years of work. We had 400 members but only 10-15 active members. Basic branch processes were a huge effort as we struggled to fill committee roles. One person (the then secretary) was burning herself out doing all the work just phoning people up to make sure these meetings and events were even happening, if she stopped the branch would have just vanished. 

I was door knocking again but this time it seemed to me to be a huge waste of time, like we were going around collecting peoples phone numbers and emails, getting them to sign a petition for us, it made me uncomfortable in the same way that I had felt door knocking for the Labour party: what was the point of collecting any of this information, where was it going? 

At meeting it always felt so busy, like voting on stuff, needing a new campaign (this month we are running a hustings, next month something to do with busses, next month after that... etc) and it felt that this structure was not helping us at all. It was like being in a bad dream. I wanted to tell people, wait stop, whats going on, can we just address losing all of our experienced organisers? 

The members making up the core of this second generation of ACORN Sheffield filled me in on what had happened (and their explanation was as almost as vague as the official line "official" ACORN explanation I was given)'' They told me it was messed up what had happened to the previous generation of organisers but that they were sure that the next National Conference there would be a window to make changes that would prevent this kind of thing happening again. 

* Positives:
I want to put in a short interlude of some of the highlights of my time in ACORN Sheffield. I think one reason I never saw to eye with people in my 
* Despair:
As I gained more and more understanding of the problems of ACORN I grew more despairing. I read the account of what had happened to ACORN Oxford and it seemed to fit as an explanation as to what had happened in Sheffield. THe 

Why did I feel despair:
- Carrying out member defense as part of ACORN felt despairing for so many reasons. 

When I first joined I didn't want to have to think about high-level questions around strategy or union structure, I just wanted to learn from people who had more experience than me. The organisers who I did find inspiring and who had grown ACORN Sheffield rapidly all left in 2022 and with them the knowledge that they could have passed on 

I think the biggest frustration I felt throughout the time in ACORN is that there was no awareness that the struggle to democratise the union and the struggle to grow capacity as a branch are tightly linked. I might write an article on this but a few examples of what I mean include:
- most obvious example: we lost all the knowledgable organisers, e.g.  

The reason this was so frustrating was because the active membership in ACORN Sheffield who were aware of  

* Relief: Generation 3 of ACORN Sheffield?
ACORN Sheffield was actually growing slowly (although extremely slowly and in spite of staff who did not help us and whose main contribution was to tell us not to do things, or take away out WhatsApp chat).

We were anticipating the National Conference. It had been delayed in 2023 for 'cost saving reasons'.'' I hadn't been involved at all in coming up with motions but that idea of making Nick Ballards position elected seemed like a really obvious one. 

The response ACORN National made to this motion being submitted completely tanked any hope anyone in ACORN Sheffield had that we could make meaningful democratic reforms. The grounds for kicking out the entire committee was because the motion was submitted late being a breach of democratic procedure. What a joke.

* Notes:
'the reason I would later discover for this group being deleted was some spurious legal bullshit relating to the ongoing Zobia Rafique case, I could explain it in postscript later if I have time. 
'' The I guess "official" line was that the mass exodus resulted from "personal drama, bullying allegations, covid and recruiting too heavily from a student population". The explanation that the other few members gave me was also pretty unsatisfactory, but something like conflict with ACORN National, this is corroborated by me meeting an ex-ACORN Sheffield member who was actually very active who described Nick Ballard as being a Stalinist... interesting

'' (the Chartists literally used to meet up in parks and public spaces for their meetings but apparently we can't organise that)
